version: "3.8"
services:
    backend:
        build: ./backend
        ports:
            - "4000:4000"
        env_file:
            - ./backend/.env
        depends_on:
            - mongo

    frontend:
        build: ./frontend
        ports:
            - "5173:5173"
        depends_on:
            - backend

    mongo:
        image: mongo
        container_name: mongo_db
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin
        ports:
            - "27017:27017"
